CREATE TABLE INVESTIGA (
	DNIPolicia INT NOT NULL,
	codCaso INT NOT NULL,
	PRIMARY KEY (DNIPolicia, codCaso),
	FOREIGN KEY (DNIPolicia) REFERENCES POLICIA(DNI),
	FOREIGN KEY (codCaso) REFERENCES CASO(codCaso)
);