CREATE TABLE ENCERRAR (
	DNIDelincuente INT PRIMARY KEY,
	codCalabozo INT NOT NULL,
	FOREIGN KEY(DNIDelincuente) REFERENCES DELINCUENTE(DNI),
	FOREIGN KEY(codCalabozo) REFERENCES CALABOZO(codCalabozo)
);