CREATE TABLE USO_ARMA (
	DNIPolicia INT NOT NULL,
	CodArma INT NOT NULL,
	Habilidad INT CHECK(Habilidad BETWEEN  1 AND 10),
	PRIMARY KEY(DNIPolicia, CodArma),
	FOREIGN KEY(DNIPolicia) REFERENCES POLICIA(DNI),
	FOREIGN KEY(CodArma) REFERENCES ARMA(CodArma)
);