CREATE TABLE INVOLUCRADO (
	DNIDelincuente INT NOT NULL,
	codCaso INT NOT NULL,
	PRIMARY KEY (DNIDelincuente, codCaso),
	FOREIGN KEY (DNIDelincuente) REFERENCES DELINCUENTE(DNI),
	FOREIGN KEY (codCaso) REFERENCES CASO(codCaso)
);